<?php
$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  #AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  $AAAAAAAAAAAAAAAAAAAAAAAA
  

  $AAAAAAAAAAAAAAAAAAAAAAAA
  
?>
